sudo: required

language: java

services:
  - docker
  
before_install:
  - docker build -t tracesoftware/clamav-rest:latest .

script:
  - docker-compose up
  - sleep 20
  - mvn test
  - ./testi.sh

after_success:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker push tracesoftware/clamav-rest:latest
