sudo: required

language: java

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker build -t tracesoftware/clamav-rest:latest .

script:
  - docker-compose up -d
  - sleep 20
  - mvn test
  - ./testi.sh

after_success:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker push tracesoftware/clamav-rest:latest
